version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - fredrikhr
  ignore:
  - dependency-name: AWSSDK.CognitoIdentityProvider
    versions:
    - 3.5.1.22
    - 3.5.1.23
    - 3.5.1.24
    - 3.5.1.25
    - 3.5.1.26
    - 3.5.1.27
    - 3.5.1.28
    - 3.5.1.29
    - 3.5.1.30
    - 3.5.1.31
    - 3.5.1.32
    - 3.5.1.33
    - 3.5.1.34
    - 3.5.1.35
    - 3.5.1.36
    - 3.5.1.37
    - 3.7.0
    - 3.7.0.1
    - 3.7.0.10
    - 3.7.0.11
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.6
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
  - dependency-name: AWSSDK.CognitoIdentity
    versions:
    - 3.5.2.10
    - 3.5.2.11
    - 3.5.2.12
    - 3.5.2.13
    - 3.5.2.14
    - 3.5.2.15
    - 3.5.2.16
    - 3.5.2.17
    - 3.5.2.18
    - 3.5.2.19
    - 3.5.2.20
    - 3.5.2.5
    - 3.5.2.6
    - 3.5.2.7
    - 3.5.2.8
    - 3.5.2.9
    - 3.7.0
    - 3.7.0.1
    - 3.7.0.10
    - 3.7.0.11
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.6
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
  - dependency-name: AWSSDK.Core
    versions:
    - 3.5.2.10
    - 3.5.2.3
    - 3.5.2.5
    - 3.5.2.6
    - 3.5.2.7
    - 3.5.2.8
    - 3.5.2.9
    - 3.5.3
    - 3.5.3.1
    - 3.5.3.2
    - 3.5.3.3
    - 3.5.3.5
    - 3.5.3.6
    - 3.5.3.7
    - 3.5.3.8
    - 3.5.3.9
    - 3.7.0
    - 3.7.0.1
    - 3.7.0.10
    - 3.7.0.11
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.5
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
  - dependency-name: MQTTnet
    versions:
    - 3.0.14
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - fredrikhr
