name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   github
variables:
  - group: thnetii.aws-sdk-net-ext
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - script: |
        dotnet user-secrets set -p test/THNETII.AWSSDK.Extensions.Test "TelenorMic:Credentials:Hostname" "$(TelenorMic.Credentials.Hostname)"
        dotnet user-secrets set -p test/THNETII.AWSSDK.Extensions.Test "TelenorMic:Credentials:Username" "$(TelenorMic.Credentials.Username)"
        dotnet user-secrets set -p test/THNETII.AWSSDK.Extensions.Test "TelenorMic:Credentials:Username" "$(TelenorMic.Credentials.Username)"
      displayName: dotnet user-secrets set -p test/THNETII.AWSSDK.Extensions.Test
    poststeps:
    - script: |
        dotnet user-secrets clear -p test/THNETII.AWSSDK.Extensions.Test
      displayName: dotnet user-secrets clear -p test/THNETII.AWSSDK.Extensions.Test
      condition: always()
