name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   github
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: DownloadSecureFile@1
      displayName:  Download Telenor MIC login credentials
      inputs:
        secureFile: TelenorMicCredentials.json
    - task: CopyFiles@2
      displayName:  Copy Telenor MIC credentials to Unit Test source directory
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents:     TelenorMicCredentials.json
        targetFolder: $(Build.SourcesDirectory)/test/THNETII.AWSSDK.Extensions.Test/TestParameters
        overWrite:    true
